sudo: required
services:
  - docker

before_install:
  - docker build -t wojciechkrukar/docker-react -f Dockerfile.dev .

script:
  - docker run wojciechkrukar/docker-react npm run test -- --coverage
# deploy:
